# Generated by Django 5.2.9 on 2025-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('Operator', 'Operator'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], default='Viewer', help_text='User role in the system', max_length=20),
        ),
    ]
