# Generated by Django 5.2.9 on 2025-12-21 17:29

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account lockout expiration time', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='User email address (required and unique)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, help_text="User's full name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, db_index=True, help_text='Organization name for multi-tenant support', max_length=255, null=True, validators=[accounts.validators.validate_organization_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True, validators=[accounts.validators.validate_phone_number]),
        ),
    ]
