# Generated by Django 5.2.9 on 2025-12-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email address has been verified"),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, help_text='6-digit verification code for email verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiration time for the verification code', null=True),
        ),
    ]
