# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.core.validators
import django.db.models.deletion
import templates.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the template', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the template', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the template', null=True)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', help_text='Template orientation', max_length=20)),
                ('width', models.PositiveIntegerField(default=1920, help_text='Template width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=1080, help_text='Template height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview thumbnail image for the template', null=True, upload_to=templates.models.template_thumbnail_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is currently active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this template was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Template version number', validators=[django.core.validators.MinValueValidator(1)])),
                ('config_json', models.JSONField(default=templates.models.default_json_dict, help_text='Template configuration in JSON format (required)')),
                ('meta_data', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Additional metadata in JSON format (optional)')),
                ('assigned_schedules', models.ManyToManyField(blank=True, help_text='Schedules assigned to this template', related_name='templates', to='signage.schedule')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('screens', models.ManyToManyField(blank=True, help_text='Screens that have this template assigned', related_name='templates', to='signage.screen')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates_template',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the schedule', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the schedule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the schedule', null=True)),
                ('start_time', models.DateTimeField(help_text='Start time for the schedule')),
                ('end_time', models.DateTimeField(help_text='End time for the schedule')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the schedule is currently active')),
                ('repeat_type', models.CharField(choices=[('none', 'None (One-time)'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='How often the schedule should repeat', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority level (higher values override lower ones in conflicts)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this schedule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this schedule was last updated')),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='Last time this schedule was executed', null=True)),
                ('is_currently_running', models.BooleanField(default=False, help_text='Whether this schedule is currently active and running')),
                ('screens', models.ManyToManyField(blank=True, help_text='Screens where this schedule should run', related_name='schedules', to='signage.screen')),
                ('template', models.ForeignKey(help_text='Template to be displayed in this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='templates.template')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'templates_schedule',
                'ordering': ['-priority', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the layer', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the layer', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the layer', null=True)),
                ('x', models.PositiveIntegerField(default=0, help_text='X position (left) in pixels from template origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.PositiveIntegerField(default=0, help_text='Y position (top) in pixels from template origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField(default=100, help_text='Layer width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=100, help_text='Layer height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('z_index', models.PositiveIntegerField(default=0, help_text='Z-index for display order (higher values appear on top)', validators=[django.core.validators.MinValueValidator(0)])),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex code like #FFFFFF or color name)', max_length=50, null=True)),
                ('opacity', models.FloatField(default=1.0, help_text='Layer opacity (0.0 = transparent, 1.0 = opaque)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('animation_type', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide', 'Slide')], default='none', help_text='Type of animation to apply to the layer', max_length=20)),
                ('animation_duration', models.FloatField(default=0.0, help_text='Animation duration in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the layer is currently active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this layer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this layer was last updated')),
                ('template', models.ForeignKey(help_text='Template that this layer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='templates.template')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'db_table': 'templates_layer',
                'ordering': ['template', 'z_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the widget', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the widget', max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('clock', 'Clock'), ('webview', 'Web View'), ('chart', 'Chart')], help_text='Type of widget content', max_length=20)),
                ('content_url', models.URLField(blank=True, help_text='URL or file path for image/video/webview content', max_length=500, null=True)),
                ('content_json', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Dynamic or structured data for widget content')),
                ('font_size', models.PositiveIntegerField(blank=True, help_text='Font size in pixels (used for text widgets)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(blank=True, help_text='Color (hex code or color name) for text or background', max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text='Text alignment (used for text widgets)', max_length=10, null=True)),
                ('autoplay', models.BooleanField(default=False, help_text='Whether to autoplay video or animated widgets')),
                ('x', models.PositiveIntegerField(default=0, help_text='X position (left) in pixels from layer origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.PositiveIntegerField(default=0, help_text='Y position (top) in pixels from layer origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField(default=100, help_text='Widget width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=100, help_text='Widget height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('z_index', models.PositiveIntegerField(default=0, help_text='Z-index for display order within layer (higher values appear on top)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the widget is currently active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this widget was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this widget was last updated')),
                ('layer', models.ForeignKey(help_text='Layer that this widget belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='templates.layer')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'db_table': 'templates_widget',
                'ordering': ['layer', 'z_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the content', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the content', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the content', null=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('webview', 'Web View'), ('chart', 'Chart'), ('json', 'JSON Data')], help_text='Type of content', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='URL or file path for local or remote files (image/video/webview)', max_length=1000, null=True, validators=[django.core.validators.URLValidator()])),
                ('content_json', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Dynamic or structured data for content')),
                ('text_content', models.TextField(blank=True, help_text='Manual text content for text type (alternative to file upload)', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Display duration in seconds (for slideshows or videos)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('autoplay', models.BooleanField(default=False, help_text='Whether to autoplay video or animated content')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of content in a widget (for playlists or slideshows)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the content is currently active and visible')),
                ('downloaded', models.BooleanField(default=False, help_text='Whether content is cached locally on Screen')),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Status of content download to screen', max_length=20)),
                ('last_download_attempt', models.DateTimeField(blank=True, help_text='Last time download was attempted', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of download retry attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_path', models.CharField(blank=True, help_text='Internal storage path for the file (S3 key or local path)', max_length=500, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of file content for integrity verification', max_length=64, null=True)),
                ('hash_algorithm', models.CharField(default='sha256', help_text='Hash algorithm used for file_hash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this content was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this content was last updated')),
                ('widget', models.ForeignKey(help_text='Widget that this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='templates.widget')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'templates_content',
                'ordering': ['widget', 'order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active', 'created_at'], name='templates_t_is_acti_e790f8_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_by', 'is_active'], name='templates_t_created_84b12d_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['orientation', 'is_active'], name='templates_t_orienta_4b8890_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['template', 'is_active'], name='templates_s_templat_b57610_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_time', 'end_time'], name='templates_s_start_t_a92484_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='templates_s_is_acti_8fc5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['repeat_type', 'is_active'], name='templates_s_repeat__042be0_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['priority', 'is_active'], name='templates_s_priorit_671735_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_currently_running', 'start_time'], name='templates_s_is_curr_9d97a2_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['template', 'z_index'], name='templates_l_templat_c5cc72_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['template', 'is_active'], name='templates_l_templat_1ec82d_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['is_active', 'z_index'], name='templates_l_is_acti_9edc82_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['layer', 'z_index'], name='templates_w_layer_i_e3ba77_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['layer', 'is_active'], name='templates_w_layer_i_26e936_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['type', 'is_active'], name='templates_w_type_57db17_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['is_active', 'z_index'], name='templates_w_is_acti_fc8513_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['widget', 'order'], name='templates_c_widget__5af1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['widget', 'is_active'], name='templates_c_widget__13ae7b_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['type', 'is_active'], name='templates_c_type_aee310_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['download_status', 'downloaded'], name='templates_c_downloa_d30dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['widget', 'download_status'], name='templates_c_widget__2dd6a7_idx'),
        ),
    ]
