# Generated by Django 5.2.9 on 2026-01-02 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels (for image content)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels (for image content)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Video duration in seconds (for video content)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='widget',
            field=models.ForeignKey(blank=True, help_text='Widget that this content belongs to (optional - allows standalone media library)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='templates.widget'),
        ),
    ]
