# Generated by Django 5.2.9 on 2025-12-12 17:35

import django.core.validators
import django.db.models.deletion
import templates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the widget', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the widget', max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('clock', 'Clock'), ('webview', 'Web View'), ('chart', 'Chart')], help_text='Type of widget content', max_length=20)),
                ('content_url', models.URLField(blank=True, help_text='URL or file path for image/video/webview content', max_length=500, null=True)),
                ('content_json', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Dynamic or structured data for widget content')),
                ('font_size', models.PositiveIntegerField(blank=True, help_text='Font size in pixels (used for text widgets)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(blank=True, help_text='Color (hex code or color name) for text or background', max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text='Text alignment (used for text widgets)', max_length=10, null=True)),
                ('autoplay', models.BooleanField(default=False, help_text='Whether to autoplay video or animated widgets')),
                ('x', models.PositiveIntegerField(default=0, help_text='X position (left) in pixels from layer origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.PositiveIntegerField(default=0, help_text='Y position (top) in pixels from layer origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField(default=100, help_text='Widget width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=100, help_text='Widget height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('z_index', models.PositiveIntegerField(default=0, help_text='Z-index for display order within layer (higher values appear on top)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the widget is currently active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this widget was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this widget was last updated')),
                ('layer', models.ForeignKey(help_text='Layer that this widget belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='templates.layer')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'db_table': 'templates_widget',
                'ordering': ['layer', 'z_index', 'name'],
                'indexes': [models.Index(fields=['layer', 'z_index'], name='templates_w_layer_i_e3ba77_idx'), models.Index(fields=['layer', 'is_active'], name='templates_w_layer_i_26e936_idx'), models.Index(fields=['type', 'is_active'], name='templates_w_type_57db17_idx'), models.Index(fields=['is_active', 'z_index'], name='templates_w_is_acti_fc8513_idx')],
            },
        ),
    ]
