# Generated by Django 5.2.9 on 2025-12-16 16:44

import django.core.validators
import django.db.models.deletion
import templates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_alter_screen_active_template_delete_template'),
        ('templates', '0002_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the content', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the content', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the content', null=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('webview', 'Web View'), ('chart', 'Chart'), ('json', 'JSON Data')], help_text='Type of content', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='URL or file path for local or remote files (image/video/webview)', max_length=1000, null=True, validators=[django.core.validators.URLValidator()])),
                ('content_json', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Dynamic or structured data for content')),
                ('duration', models.FloatField(blank=True, help_text='Display duration in seconds (for slideshows or videos)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('autoplay', models.BooleanField(default=False, help_text='Whether to autoplay video or animated content')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of content in a widget (for playlists or slideshows)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the content is currently active and visible')),
                ('downloaded', models.BooleanField(default=False, help_text='Whether content is cached locally on Screen')),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Status of content download to screen', max_length=20)),
                ('last_download_attempt', models.DateTimeField(blank=True, help_text='Last time download was attempted', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of download retry attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this content was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this content was last updated')),
                ('widget', models.ForeignKey(help_text='Widget that this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='templates.widget')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'templates_content',
                'ordering': ['widget', 'order', 'name'],
                'indexes': [models.Index(fields=['widget', 'order'], name='templates_c_widget__5af1ee_idx'), models.Index(fields=['widget', 'is_active'], name='templates_c_widget__13ae7b_idx'), models.Index(fields=['type', 'is_active'], name='templates_c_type_aee310_idx'), models.Index(fields=['download_status', 'downloaded'], name='templates_c_downloa_d30dc3_idx'), models.Index(fields=['widget', 'download_status'], name='templates_c_widget__2dd6a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the schedule', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the schedule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the schedule', null=True)),
                ('start_time', models.DateTimeField(help_text='Start time for the schedule')),
                ('end_time', models.DateTimeField(help_text='End time for the schedule')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the schedule is currently active')),
                ('repeat_type', models.CharField(choices=[('none', 'None (One-time)'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='How often the schedule should repeat', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority level (higher values override lower ones in conflicts)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this schedule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this schedule was last updated')),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='Last time this schedule was executed', null=True)),
                ('is_currently_running', models.BooleanField(default=False, help_text='Whether this schedule is currently active and running')),
                ('screens', models.ManyToManyField(blank=True, help_text='Screens where this schedule should run', related_name='schedules', to='signage.screen')),
                ('template', models.ForeignKey(help_text='Template to be displayed in this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='templates.template')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'templates_schedule',
                'ordering': ['-priority', 'start_time', 'name'],
                'indexes': [models.Index(fields=['template', 'is_active'], name='templates_s_templat_b57610_idx'), models.Index(fields=['start_time', 'end_time'], name='templates_s_start_t_a92484_idx'), models.Index(fields=['is_active', 'start_time', 'end_time'], name='templates_s_is_acti_8fc5b0_idx'), models.Index(fields=['repeat_type', 'is_active'], name='templates_s_repeat__042be0_idx'), models.Index(fields=['priority', 'is_active'], name='templates_s_priorit_671735_idx'), models.Index(fields=['is_currently_running', 'start_time'], name='templates_s_is_curr_9d97a2_idx')],
            },
        ),
    ]
