# Generated by Django 5.2.9 on 2025-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_content_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of file content for integrity verification', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='hash_algorithm',
            field=models.CharField(default='sha256', help_text='Hash algorithm used for file_hash', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Internal storage path for the file (S3 key or local path)', max_length=500, null=True),
        ),
    ]
