# Generated by Django 5.2.9 on 2025-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_content_file_hash_content_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, help_text='Manual text content for text type (alternative to file upload)', null=True),
        ),
    ]
