# Generated by Django 5.0.1 on 2026-04-02 12:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tiered_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Visitor', 'Visitor')], default='Employee', help_text='User role in the system', max_length=20),
        ),
    ]
