# Generated by Django 5.0.1 on 2026-04-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_visitor_role_and_template_sample'),
        ('saas_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='SaaS customer account (Platform); optional for legacy installs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='saas_platform.tenant'),
        ),
    ]
