# Generated by Django 5.0.1 on 2026-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes_hash',
            field=models.TextField(blank=True, default='', help_text='JSON list of hashed one-time backup codes (empty when none)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='When True, login requires a TOTP code after password'),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g. google, azure, oidc', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_subject',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable subject identifier from the IdP', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 TOTP secret (empty when 2FA not configured)', max_length=64),
        ),
    ]
