# Generated by Django 5.0.1 on 2026-04-02 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_twofa_sso'),
        ('saas_platform', '0003_saas_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Product onboarding checklist progress (tenant-scoped keys)'),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('role', models.CharField(default='Employee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='saas_platform.tenant')),
            ],
            options={
                'db_table': 'accounts_user_invitation',
                'ordering': ['-created_at'],
            },
        ),
    ]
