# Generated by Django 5.0.1 on 2026-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_saas_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_lock_reason',
            field=models.CharField(blank=True, default='', help_text='Reason shown in admin tools when account is locked', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_lock_until',
            field=models.DateTimeField(blank=True, help_text='Optional expiration; null means locked until manually unlocked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_locked',
            field=models.BooleanField(default=False, help_text='Developer-imposed hard lock — blocks login and revokes sessions'),
        ),
    ]
