# Generated by Django 5.2.9 on 2026-05-18 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_admin_lock_reason_user_admin_lock_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(blank=True, default='', max_length=64)),
                ('plan_name', models.CharField(blank=True, default='', max_length=128)),
                ('plan_interval', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('none', 'None'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('unpaid', 'Unpaid')], default='none', max_length=20)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider_customer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('device_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'accounts_user_subscription',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='accounts_us_status_3b1388_idx'), models.Index(fields=['plan_key', 'status'], name='accounts_us_plan_ke_85d9fd_idx')],
            },
        ),
    ]
