# Generated by Django 5.2.9 on 2025-12-17 17:36

import django.core.validators
import django.db.models.deletion
import notifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the channel', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], db_index=True, help_text='Channel type', max_length=20)),
                ('name', models.CharField(help_text='Human-readable name for this channel', max_length=255)),
                ('config', notifications.models.EncryptedJSONField(help_text='Encrypted channel configuration (provider credentials, endpoints, etc.)')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this channel is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this channel was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this channel was last updated')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization/user this channel belongs to (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'db_table': 'notifications_channel',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', primary_key=True, serialize=False)),
                ('event_key', models.CharField(db_index=True, help_text="Event identifier (e.g., 'screen.offline', 'command.failed')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', help_text='Default severity level for this event', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is active and can trigger notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event was created')),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
                'db_table': 'notifications_event',
                'ordering': ['event_key'],
                'indexes': [models.Index(fields=['event_key', 'is_active'], name='notificatio_event_k_c3fedf_idx'), models.Index(fields=['severity', 'is_active'], name='notificatio_severit_dcb26b_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the rule', primary_key=True, serialize=False)),
                ('severity_threshold', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Minimum severity to trigger this rule', max_length=20)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Cooldown period in seconds (0-86400)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)])),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this rule was last updated')),
                ('channels', models.ManyToManyField(help_text='Channels to use for this rule', related_name='rules', to='notifications.notificationchannel')),
                ('event', models.ForeignKey(help_text='Event that triggers this rule', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notifications.notificationevent')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization/user this rule belongs to (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
                'db_table': 'notifications_rule',
                'ordering': ['-is_enabled', 'event__event_key'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the log entry', primary_key=True, serialize=False)),
                ('event_key', models.CharField(db_index=True, help_text='Event key that triggered this notification', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Delivery status', max_length=20)),
                ('provider_response', models.TextField(blank=True, help_text='Sanitized response from provider (no secrets)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Idempotency key for deduplication', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was successfully sent', null=True)),
                ('channel', models.ForeignKey(help_text='Channel used for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationchannel')),
                ('rule', models.ForeignKey(blank=True, help_text='Rule that triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationrule')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notifications_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['type', 'is_enabled'], name='notificatio_type_7e4b52_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['organization', 'is_enabled'], name='notificatio_organiz_c79a23_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['organization', 'is_enabled'], name='notificatio_organiz_c01a39_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['event', 'is_enabled'], name='notificatio_event_i_5c2b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['is_enabled', 'severity_threshold'], name='notificatio_is_enab_df8c66_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_key', 'status'], name='notificatio_event_k_5577e8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_b23f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['idempotency_key'], name='notificatio_idempot_6d55eb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at', 'status'], name='notificatio_created_38a3b9_idx'),
        ),
    ]
