"""
Django settings for Screengram project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file in project root (one level up from BackEnd)
# BASE_DIR is BackEnd, so .env is in BASE_DIR.parent
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(dotenv_path=PROJECT_ROOT / '.env')

# Import Fernet for notification encryption key generation
try:
    from cryptography.fernet import Fernet
except ImportError:
    Fernet = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set SECRET_KEY as an environment variable
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7szgl4mmm9n0!&u3d4-=iut39ffowsvlr^r9img3r!izj=n3tq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
    "http://localhost:3000",  # Alternative dev port
    "http://127.0.0.1:3000",
]

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Account Lockout Configuration
ACCOUNT_LOCKOUT_ENABLED = os.environ.get('ACCOUNT_LOCKOUT_ENABLED', 'True').lower() == 'true'
MAX_LOGIN_ATTEMPTS = int(os.environ.get('MAX_LOGIN_ATTEMPTS', '5'))
LOCKOUT_DURATION = int(os.environ.get('LOCKOUT_DURATION', '900'))  # 15 minutes


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers for cross-origin requests
    'channels',  # Django Channels for WebSocket support
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT Authentication
    'core',  # Core infrastructure (caching, rate limiting, audit, backup)
    'accounts',  # App for User management (must be before other apps)
    'signage',  # App for Screen management
    'templates',  # App for Template management
    'commands',  # App for Command management
    'log',  # App for centralized logging and monitoring
    'notifications',  # App for notification system
    'bulk_operations',  # App for bulk operations
    'content_validation',  # App for content validation
    'analytics',  # App for analytics dashboard
    'drf_spectacular',  # OpenAPI/Swagger documentation
    'api_docs',  # API documentation configuration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be as high as possible)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'log.middleware.ErrorLoggingMiddleware',  # Error logging middleware (must be after auth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.rate_limiting.RateLimitMiddleware',  # Rate limiting middleware

]

ROOT_URLCONF = 'Screengram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Screengram.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if SQLite should be used (fallback for development without Docker)
USE_SQLITE = os.environ.get('USE_SQLITE', 'False').lower() == 'true'

if USE_SQLITE:
    # SQLite database (fallback for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL database (production/development with Docker)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'screengram_db'),
            'USER': os.environ.get('DB_USER', 'screengram_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'full_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User-uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

# CRITICAL: Normalize MEDIA_ROOT to absolute path to prevent path traversal issues
# On Windows, this ensures paths like C:\Work\Project\...\media are properly normalized
MEDIA_ROOT = os.path.abspath(os.path.normpath(str(BASE_DIR / 'media')))
MEDIA_URL = '/media/'

# Base URL for building absolute URLs (used in serializers)
# In production, set this to your domain (e.g., 'https://yourdomain.com')
BASE_URL = os.environ.get('BASE_URL', 'http://localhost:8000')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project

AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # TEMPORARY: Changed from IsAuthenticated to test if 401 disappears
        # 'rest_framework.permissions.IsAuthenticated',  # Original setting - uncomment after testing
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Django Channels Configuration
ASGI_APPLICATION = 'Screengram.asgi.application'

# Channel Layers Configuration
# For development: use in-memory channel layer
# For production: use Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # For production with Redis, use:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}

# Security settings for screen communication
SCREEN_COMMUNICATION = {
    'TIMESTAMP_TOLERANCE': 300,  # 5 minutes
    'NONCE_CACHE_TIMEOUT': 3600,  # 1 hour
    'RATE_LIMIT_COMMANDS_PER_MINUTE': 60,
    'WEBSOCKET_TIMEOUT': 30,  # seconds
}

# File Storage Configuration
# Supports both Local File System and Amazon S3
# Set USE_S3_STORAGE=True in environment to use S3, otherwise uses local storage

USE_S3_STORAGE = False  # Set to True to use S3, False for local storage

if USE_S3_STORAGE:
    # AWS S3 Configuration
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # AWS Credentials (set via environment variables in production)
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'screengram-content')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    
    # S3 Security Settings
    AWS_QUERYSTRING_AUTH = False  # Don't add query string auth to URLs (use signed URLs instead)
    AWS_S3_FILE_OVERWRITE = False  # Don't overwrite files with same name
    AWS_DEFAULT_ACL = 'private'  # Files are private by default
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache for 1 day
    }
    
    # Signed URL expiration (in seconds) - 1 hour default
    AWS_S3_SIGNED_URL_EXPIRATION = 3600
    
    # Custom domain (optional)
    # AWS_S3_CUSTOM_DOMAIN = 'cdn.example.com'
else:
    # Local File Storage (Development/Default)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Content Storage Settings
CONTENT_STORAGE = {
    'MAX_FILE_SIZE': 500 * 1024 * 1024,  # 500 MB max file size
    'ALLOWED_IMAGE_TYPES': ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml'],
    'ALLOWED_VIDEO_TYPES': ['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime'],
    'ALLOWED_WEBVIEW_TYPES': ['text/html', 'application/xhtml+xml'],
    'SIGNED_URL_EXPIRATION': 3600,  # 1 hour for signed URLs
    'ENABLE_HASH_VALIDATION': True,  # Enable file integrity checking via hash
    'HASH_ALGORITHM': 'sha256',  # Hash algorithm for integrity checking
}

# Notification System Configuration
NOTIFICATIONS_ASYNC = True  # Use Celery for async delivery (set False for sync in development)
# Generate encryption key if not set (for development only - use env var in production)
if Fernet:
    NOTIFICATION_ENCRYPTION_KEY = os.environ.get('NOTIFICATION_ENCRYPTION_KEY', Fernet.generate_key().decode())
else:
    NOTIFICATION_ENCRYPTION_KEY = os.environ.get('NOTIFICATION_ENCRYPTION_KEY', None)

# Celery Configuration (for async notifications)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production: uncomment and configure one of the following SMTP backends
# Gmail SMTP example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your-email@gmail.com')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your-app-password')

# SendGrid example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')

# Generic SMTP example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
# EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
# EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = 'no-reply@screengram.com'

# OpenAPI/Swagger Documentation Settings
try:
    from .schema_settings import SPECTACULAR_SETTINGS
except ImportError:
    # Fallback if schema_settings doesn't exist yet
    SPECTACULAR_SETTINGS = {
        'TITLE': 'ScreenGram API',
        'DESCRIPTION': 'ScreenGram Digital Signage Management API',
        'VERSION': '1.0.0',
        'SCHEMA_PATH_PREFIX': '/api/',
    }

# Caching Configuration
# For production: use Redis
# For development: use LocMemCache (fallback)
USE_REDIS_CACHE = os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true'

if USE_REDIS_CACHE:
    # Use Django's built-in Redis cache backend (Django 5.2+)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_CACHE_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                # Optional: uncomment if using django-redis
                # 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'screengram',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
        }
    }
else:
    # Development: use in-memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'screengram-cache',
        }
    }

# Rate Limiting Configuration
RATE_LIMITING = {
    'ENABLED': os.environ.get('RATE_LIMITING_ENABLED', 'True').lower() == 'true',
    'STRATEGY': 'combined',  # 'user', 'ip', 'role', 'endpoint', 'combined'
    'DEFAULT_PER_MINUTE': 60,
    'DEFAULT_PER_HOUR': 1000,
    'DEFAULT_PER_DAY': 10000,
    
    # Per-role rate limits (overrides defaults)
    'PER_ROLE_LIMITS': {
        'SuperAdmin': {
            'per_minute': 200,
            'per_hour': 5000,
            'per_day': 50000,
        },
        'Admin': {
            'per_minute': 150,
            'per_hour': 3000,
            'per_day': 30000,
        },
        'Manager': {
            'per_minute': 100,
            'per_hour': 2000,
            'per_day': 20000,
        },
        'Operator': {
            'per_minute': 60,
            'per_hour': 1000,
            'per_day': 10000,
        },
        'Viewer': {
            'per_minute': 30,
            'per_hour': 500,
            'per_day': 5000,
        },
    },
    
    # Endpoint-specific limits (optional)
    'ENDPOINTS': {
        # '/api/analytics/': {
        #     'strategy': 'user',
        #     'limits': {
        #         'per_minute': 30,
        #         'per_hour': 500,
        #     },
        # },
    },
}

# Backup Configuration
BACKUP_CONFIG = {
    'BACKUP_DIR': os.environ.get('BACKUP_DIR', BASE_DIR / 'backups'),
    'RETENTION_DAYS': int(os.environ.get('BACKUP_RETENTION_DAYS', '30')),
    'ENABLE_AUTO_BACKUP': os.environ.get('ENABLE_AUTO_BACKUP', 'False').lower() == 'true',
    'AUTO_BACKUP_SCHEDULE': {
        'database': 'daily',  # 'daily', 'weekly', 'monthly'
        'media': 'weekly',
        'full': 'monthly',
    },
    'BACKUP_TIME': '02:00',  # Time to run scheduled backups (UTC)
    'COMPRESSION': True,
    'ENCRYPTION': os.environ.get('BACKUP_ENCRYPTION', 'False').lower() == 'true',
}

# Audit Logging Configuration
AUDIT_LOGGING = {
    'ENABLED': os.environ.get('AUDIT_LOGGING_ENABLED', 'True').lower() == 'true',
    'LOG_READS': os.environ.get('AUDIT_LOG_READS', 'False').lower() == 'true',  # Log read operations
    'RETENTION_DAYS': int(os.environ.get('AUDIT_RETENTION_DAYS', '365')),  # Keep logs for 1 year
    'AUTO_CLEANUP': os.environ.get('AUDIT_AUTO_CLEANUP', 'True').lower() == 'true',
}
