# Generated by Django 5.0.1 on 2026-04-01 10:09

import django.db.models.deletion
import templates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_widget_add_date_weekday_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('marquee', 'Marquee'), ('weather', 'Weather'), ('qr_action', 'QR Action'), ('image', 'Image'), ('video', 'Video'), ('clock', 'Clock'), ('date', 'Date'), ('weekday', 'Weekday'), ('webview', 'Web View'), ('chart', 'Chart')], help_text='Type of widget content', max_length=20),
        ),
        migrations.CreateModel(
            name='QRActionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('default_url', models.URLField(max_length=1000)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('error_correction_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('Q', 'Quartile'), ('H', 'High')], default='H', max_length=1)),
                ('settings_json', models.JSONField(blank=True, default=templates.models.default_json_dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_action_link', to='templates.widget')),
            ],
            options={
                'db_table': 'templates_qr_action_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRActionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('target_url', models.URLField(max_length=1000)),
                ('start_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_json', models.JSONField(blank=True, default=templates.models.default_json_dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='templates.qractionlink')),
            ],
            options={
                'db_table': 'templates_qr_action_rule',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('resolved_url', models.URLField(max_length=1000)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('query_params', models.JSONField(blank=True, default=templates.models.default_json_dict)),
                ('source_screen', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='templates.qractionlink')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='templates.qractionrule')),
            ],
            options={
                'db_table': 'templates_qr_scan_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qractionlink',
            index=models.Index(fields=['is_active', 'created_at'], name='templates_q_is_acti_f9cbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='qractionlink',
            index=models.Index(fields=['campaign_id', 'created_at'], name='templates_q_campaig_ecc93e_idx'),
        ),
        migrations.AddIndex(
            model_name='qractionrule',
            index=models.Index(fields=['link', 'is_active', 'priority'], name='templates_q_link_id_086515_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['link', 'created_at'], name='templates_q_link_id_93f485_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['campaign_id', 'created_at'], name='templates_q_campaig_4e0960_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['created_at'], name='templates_q_created_b96666_idx'),
        ),
    ]
