# Generated by Django 5.0.1 on 2026-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0010_widget_add_album_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, visible to all Visitor users for exploration (read-only in app)'),
        ),
    ]
