# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.core.validators
import django.db.models.deletion
import log.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the download log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], help_text='Download status', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if download failed', null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='When content was successfully downloaded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this download log was created')),
            ],
            options={
                'verbose_name': 'Content Download Log',
                'verbose_name_plural': 'Content Download Logs',
                'db_table': 'log_content_download',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the validation log entry', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, help_text='ID of user who uploaded the content')),
                ('username', models.CharField(db_index=True, help_text='Username who uploaded the content', max_length=150)),
                ('content_id', models.UUIDField(blank=True, db_index=True, help_text='Content ID (if saved after validation)', null=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=500)),
                ('sanitized_filename', models.CharField(blank=True, help_text='Sanitized filename after validation', max_length=500, null=True)),
                ('content_type', models.CharField(db_index=True, help_text='Content type (image, video, text, etc.)', max_length=50)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type', max_length=255, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('security_risk', 'Security Risk')], db_index=True, default='pending', help_text='Validation status', max_length=20)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether validation passed')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors')),
                ('validation_warnings', models.JSONField(blank=True, default=list, help_text='List of validation warnings')),
                ('metadata', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Extracted metadata (dimensions, format, etc.)')),
                ('security_flags', models.JSONField(blank=True, default=list, help_text='Security flags raised during validation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When validation was performed')),
            ],
            options={
                'verbose_name': 'Content Validation Log',
                'verbose_name_plural': 'Content Validation Logs',
                'db_table': 'log_content_validation',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the error log entry', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the error occurred')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', help_text='Error severity level', max_length=20)),
                ('message', models.TextField(help_text='Error message')),
                ('stack_trace', models.TextField(blank=True, help_text='Full stack trace of the error', null=True)),
                ('endpoint', models.CharField(blank=True, db_index=True, help_text='API endpoint or URL where error occurred', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('exception_type', models.CharField(blank=True, db_index=True, help_text='Type of exception (e.g., ValueError, PermissionDenied)', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Additional error metadata')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Whether the error has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the error was marked as resolved', null=True)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'db_table': 'log_error',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScreenStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the status log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Online or offline status', max_length=20)),
                ('heartbeat_latency', models.FloatField(blank=True, help_text='Heartbeat latency in milliseconds', null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this status was recorded')),
            ],
            options={
                'verbose_name': 'Screen Status Log',
                'verbose_name_plural': 'Screen Status Logs',
                'db_table': 'log_screen_status',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the bulk operation log entry', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, help_text='ID of user who performed the operation')),
                ('username', models.CharField(db_index=True, help_text='Username who performed the operation', max_length=150)),
                ('operation_type', models.CharField(db_index=True, help_text="Type of operation (e.g., 'bulk_delete', 'bulk_update', 'bulk_activate')", max_length=100)),
                ('module', models.CharField(db_index=True, help_text="Module name (e.g., 'screens', 'templates', 'contents')", max_length=50)),
                ('item_ids', models.JSONField(default=list, help_text='List of item IDs affected by the operation')),
                ('item_count', models.PositiveIntegerField(help_text='Total number of items in the operation')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of successful operations')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of failed operations')),
                ('details', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Additional details about the operation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the operation was performed')),
            ],
            options={
                'verbose_name': 'Bulk Operation Log',
                'verbose_name_plural': 'Bulk Operation Logs',
                'db_table': 'log_bulk_operation',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='log_bulk_op_user_id_ad0854_idx'), models.Index(fields=['module', 'timestamp'], name='log_bulk_op_module_d5d62c_idx'), models.Index(fields=['operation_type', 'timestamp'], name='log_bulk_op_operati_1769bb_idx'), models.Index(fields=['username', 'timestamp'], name='log_bulk_op_usernam_411d9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the execution log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], help_text='Execution status', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When command execution started', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When command execution finished', null=True)),
                ('response_payload', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Response payload from screen (JSON format)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this execution log was created')),
                ('command', models.ForeignKey(help_text='Command that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='commands.command')),
            ],
            options={
                'verbose_name': 'Command Execution Log',
                'verbose_name_plural': 'Command Execution Logs',
                'db_table': 'log_command_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
