# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('signage', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecutionlog',
            name='screen',
            field=models.ForeignKey(help_text='Screen where command was executed', on_delete=django.db.models.deletion.CASCADE, related_name='command_execution_logs', to='signage.screen'),
        ),
        migrations.AddField(
            model_name='contentdownloadlog',
            name='content',
            field=models.ForeignKey(help_text='Content that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='templates.content'),
        ),
        migrations.AddField(
            model_name='contentdownloadlog',
            name='screen',
            field=models.ForeignKey(help_text='Screen where content was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='content_download_logs', to='signage.screen'),
        ),
        migrations.AddIndex(
            model_name='contentvalidationlog',
            index=models.Index(fields=['user_id', 'timestamp'], name='log_content_user_id_d76078_idx'),
        ),
        migrations.AddIndex(
            model_name='contentvalidationlog',
            index=models.Index(fields=['content_type', 'timestamp'], name='log_content_content_06d642_idx'),
        ),
        migrations.AddIndex(
            model_name='contentvalidationlog',
            index=models.Index(fields=['validation_status', 'timestamp'], name='log_content_validat_cda49d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentvalidationlog',
            index=models.Index(fields=['is_valid', 'timestamp'], name='log_content_is_vali_684c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentvalidationlog',
            index=models.Index(fields=['username', 'timestamp'], name='log_content_usernam_d199c9_idx'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered the error (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screenstatuslog',
            name='screen',
            field=models.ForeignKey(help_text='Screen that this status log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='signage.screen'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['command', 'created_at'], name='log_command_command_290c65_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['screen', 'created_at'], name='log_command_screen__22ad8c_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['status', 'created_at'], name='log_command_status_05398e_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['command', 'screen', 'status'], name='log_command_command_08ee33_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['content', 'created_at'], name='log_content_content_0fc4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['screen', 'created_at'], name='log_content_screen__6e99ab_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['status', 'created_at'], name='log_content_status_2d152e_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['content', 'screen', 'status'], name='log_content_content_e031e8_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['timestamp'], name='log_error_timesta_34260d_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['level', 'timestamp'], name='log_error_level_5fdba7_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['endpoint', 'timestamp'], name='log_error_endpoin_940705_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'timestamp'], name='log_error_user_id_5b63be_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['exception_type', 'timestamp'], name='log_error_excepti_175347_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['is_resolved', 'timestamp'], name='log_error_is_reso_b21510_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['screen', 'recorded_at'], name='log_screen__screen__d2d4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['status', 'recorded_at'], name='log_screen__status_898d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['screen', 'status'], name='log_screen__screen__7a73cb_idx'),
        ),
    ]
