# Generated by Django 5.2.9 on 2025-12-16 16:44

import django.core.validators
import django.db.models.deletion
import log.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
        ('signage', '0002_alter_screen_active_template_delete_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the download log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], help_text='Download status', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if download failed', null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='When content was successfully downloaded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this download log was created')),
            ],
            options={
                'verbose_name': 'Content Download Log',
                'verbose_name_plural': 'Content Download Logs',
                'db_table': 'log_content_download',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the status log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Online or offline status', max_length=20)),
                ('heartbeat_latency', models.FloatField(blank=True, help_text='Heartbeat latency in milliseconds', null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this status was recorded')),
            ],
            options={
                'verbose_name': 'Screen Status Log',
                'verbose_name_plural': 'Screen Status Logs',
                'db_table': 'log_screen_status',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the execution log entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], help_text='Execution status', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When command execution started', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When command execution finished', null=True)),
                ('response_payload', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Response payload from screen (JSON format)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this execution log was created')),
                ('command', models.ForeignKey(help_text='Command that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='commands.command')),
                ('screen', models.ForeignKey(help_text='Screen where command was executed', on_delete=django.db.models.deletion.CASCADE, related_name='command_execution_logs', to='signage.screen')),
            ],
            options={
                'verbose_name': 'Command Execution Log',
                'verbose_name_plural': 'Command Execution Logs',
                'db_table': 'log_command_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
