# Generated by Django 5.2.9 on 2025-12-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('signage', '0002_alter_screen_active_template_delete_template'),
        ('templates', '0003_content_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdownloadlog',
            name='content',
            field=models.ForeignKey(help_text='Content that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='templates.content'),
        ),
        migrations.AddField(
            model_name='contentdownloadlog',
            name='screen',
            field=models.ForeignKey(help_text='Screen where content was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='content_download_logs', to='signage.screen'),
        ),
        migrations.AddField(
            model_name='screenstatuslog',
            name='screen',
            field=models.ForeignKey(help_text='Screen that this status log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='signage.screen'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['command', 'created_at'], name='log_command_command_290c65_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['screen', 'created_at'], name='log_command_screen__22ad8c_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['status', 'created_at'], name='log_command_status_05398e_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecutionlog',
            index=models.Index(fields=['command', 'screen', 'status'], name='log_command_command_08ee33_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['content', 'created_at'], name='log_content_content_0fc4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['screen', 'created_at'], name='log_content_screen__6e99ab_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['status', 'created_at'], name='log_content_status_2d152e_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadlog',
            index=models.Index(fields=['content', 'screen', 'status'], name='log_content_content_e031e8_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['screen', 'recorded_at'], name='log_screen__screen__d2d4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['status', 'recorded_at'], name='log_screen__status_898d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='screenstatuslog',
            index=models.Index(fields=['screen', 'status'], name='log_screen__screen__7a73cb_idx'),
        ),
    ]
