# Generated by Django 5.2.9 on 2025-12-21 17:29

import log.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the bulk operation log entry', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, help_text='ID of user who performed the operation')),
                ('username', models.CharField(db_index=True, help_text='Username who performed the operation', max_length=150)),
                ('operation_type', models.CharField(db_index=True, help_text="Type of operation (e.g., 'bulk_delete', 'bulk_update', 'bulk_activate')", max_length=100)),
                ('module', models.CharField(db_index=True, help_text="Module name (e.g., 'screens', 'templates', 'contents')", max_length=50)),
                ('item_ids', models.JSONField(default=list, help_text='List of item IDs affected by the operation')),
                ('item_count', models.PositiveIntegerField(help_text='Total number of items in the operation')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of successful operations')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of failed operations')),
                ('details', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Additional details about the operation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the operation was performed')),
            ],
            options={
                'verbose_name': 'Bulk Operation Log',
                'verbose_name_plural': 'Bulk Operation Logs',
                'db_table': 'log_bulk_operation',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='log_bulk_op_user_id_ad0854_idx'), models.Index(fields=['module', 'timestamp'], name='log_bulk_op_module_d5d62c_idx'), models.Index(fields=['operation_type', 'timestamp'], name='log_bulk_op_operati_1769bb_idx'), models.Index(fields=['username', 'timestamp'], name='log_bulk_op_usernam_411d9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the validation log entry', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, help_text='ID of user who uploaded the content')),
                ('username', models.CharField(db_index=True, help_text='Username who uploaded the content', max_length=150)),
                ('content_id', models.UUIDField(blank=True, db_index=True, help_text='Content ID (if saved after validation)', null=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=500)),
                ('sanitized_filename', models.CharField(blank=True, help_text='Sanitized filename after validation', max_length=500, null=True)),
                ('content_type', models.CharField(db_index=True, help_text='Content type (image, video, text, etc.)', max_length=50)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type', max_length=255, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('security_risk', 'Security Risk')], db_index=True, default='pending', help_text='Validation status', max_length=20)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether validation passed')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors')),
                ('validation_warnings', models.JSONField(blank=True, default=list, help_text='List of validation warnings')),
                ('metadata', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Extracted metadata (dimensions, format, etc.)')),
                ('security_flags', models.JSONField(blank=True, default=list, help_text='Security flags raised during validation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When validation was performed')),
            ],
            options={
                'verbose_name': 'Content Validation Log',
                'verbose_name_plural': 'Content Validation Logs',
                'db_table': 'log_content_validation',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='log_content_user_id_d76078_idx'), models.Index(fields=['content_type', 'timestamp'], name='log_content_content_06d642_idx'), models.Index(fields=['validation_status', 'timestamp'], name='log_content_validat_cda49d_idx'), models.Index(fields=['is_valid', 'timestamp'], name='log_content_is_vali_684c2c_idx'), models.Index(fields=['username', 'timestamp'], name='log_content_usernam_d199c9_idx')],
            },
        ),
    ]
