# Generated by Django 5.2.9 on 2025-12-22 17:13

import django.db.models.deletion
import log.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_bulkoperationlog_contentvalidationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the error log entry', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the error occurred')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', help_text='Error severity level', max_length=20)),
                ('message', models.TextField(help_text='Error message')),
                ('stack_trace', models.TextField(blank=True, help_text='Full stack trace of the error', null=True)),
                ('endpoint', models.CharField(blank=True, db_index=True, help_text='API endpoint or URL where error occurred', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('exception_type', models.CharField(blank=True, db_index=True, help_text='Type of exception (e.g., ValueError, PermissionDenied)', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=log.models.default_json_dict, help_text='Additional error metadata')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Whether the error has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the error was marked as resolved', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the error (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'db_table': 'log_error',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='log_error_timesta_34260d_idx'), models.Index(fields=['level', 'timestamp'], name='log_error_level_5fdba7_idx'), models.Index(fields=['endpoint', 'timestamp'], name='log_error_endpoin_940705_idx'), models.Index(fields=['user', 'timestamp'], name='log_error_user_id_5b63be_idx'), models.Index(fields=['exception_type', 'timestamp'], name='log_error_excepti_175347_idx'), models.Index(fields=['is_resolved', 'timestamp'], name='log_error_is_reso_b21510_idx')],
            },
        ),
    ]
