"""
Django settings for PixelCast Signage (Python package: Screengram).

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv
from typing import Any, Optional, Union

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Installation state: directory for installed.lock (Docker mounts volume here)
# In Docker: /app/installation_state (volume); locally: BASE_DIR
INSTALLATION_STATE_DIR = Path(os.environ.get('INSTALLATION_STATE_DIR', str(BASE_DIR)))

# .env: Docker mounts host ./.env at /config/.env (PIXELCAST_SIGNAGE_ENV_FILE); local dev uses monorepo or BackEnd/.env
# (see BackEnd/setup/paths.py). Missing or empty file is OK — Compose still injects env vars.
from setup.paths import resolve_env_file_paths

ENV_FILE_PATH, ENV_TEMPLATE_PATH = resolve_env_file_paths(BASE_DIR)
load_dotenv(dotenv_path=ENV_FILE_PATH)


def env(key: str, default: Any = None, cast: Optional[type] = None) -> Any:
    """
    Get environment variable with safe defaults.
    
    This function provides update-safe environment variable handling:
    - If a variable is missing, returns the default (never crashes)
    - Supports type casting (str, int, bool, list)
    - Handles empty strings as missing values
    
    Args:
        key: Environment variable name
        default: Default value if variable is not set
        cast: Type to cast the value to (str, int, bool, list)
    
    Returns:
        Environment variable value (cast to type if specified) or default
    
    Examples:
        SECRET_KEY = env('SECRET_KEY', default='fallback-key')
        DEBUG = env('DEBUG', default=False, cast=bool)
        PORT = env('PORT', default=8000, cast=int)
        HOSTS = env('ALLOWED_HOSTS', default='localhost', cast=list)
    """
    def _cast_value(raw: Any) -> Any:
        if cast is None:
            return raw
        if cast == bool:
            if isinstance(raw, str):
                return raw.lower() in ('true', '1', 'yes', 'on')
            return bool(raw)
        if cast == int:
            try:
                return int(raw)
            except (ValueError, TypeError):
                return default
        if cast == float:
            try:
                return float(raw)
            except (ValueError, TypeError):
                return default
        if cast == list:
            if isinstance(raw, str):
                return [item.strip() for item in raw.split(',') if item.strip()]
            return raw if isinstance(raw, list) else [raw]
        if cast == str:
            return str(raw)
        return raw

    value = os.environ.get(key)

    # If value is not set or is empty string, use default (with cast applied)
    if value is None or value == '':
        return _cast_value(default)
    
    # Cast value when present
    return _cast_value(value)

# Import Fernet for notification encryption key generation
try:
    from cryptography.fernet import Fernet
except ImportError:
    Fernet = None

from .notification_key import default_notification_encryption_key

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEFAULT_DJANGO_SECRET_KEY = 'django-insecure-7szgl4mmm9n0!&u3d4-=iut39ffowsvlr^r9img3r!izj=n3tq'
SECRET_KEY = env('SECRET_KEY', default=_DEFAULT_DJANGO_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False, cast=bool)

_LOADING_TEST_SETTINGS = (os.environ.get('DJANGO_SETTINGS_MODULE') or '').endswith('test_settings')
if not DEBUG and not _LOADING_TEST_SETTINGS and SECRET_KEY == _DEFAULT_DJANGO_SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY must be set to a unique value in the environment when DEBUG is False.'
    )

# Allowed hosts - safe default for development
ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='localhost,127.0.0.1,backend,frontend', cast=list)

# When DEBUG is on, merge common local/Docker hostnames. Production-only ALLOWED_HOSTS in .env
# (e.g. public domains only) would otherwise cause 400 DisallowedHost for Vite's proxy
# (Host: 127.0.0.1:8000) and Compose service names (backend:8000).
if DEBUG:
    _dev_allowed = ('localhost', '127.0.0.1', 'backend', 'frontend')
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, *_dev_allowed]))

# CSRF trusted origins for HTTPS deployments behind reverse proxies (Traefik/Nginx)
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS', default='', cast=list)
if not CSRF_TRUSTED_ORIGINS:
    base_url_for_csrf = env('BASE_URL', default='')
    if isinstance(base_url_for_csrf, str) and base_url_for_csrf:
        parsed_base_url = urlparse(base_url_for_csrf)
        if parsed_base_url.scheme in ('http', 'https') and parsed_base_url.netloc:
            CSRF_TRUSTED_ORIGINS = [f"{parsed_base_url.scheme}://{parsed_base_url.netloc}"]

# HTTPS / cookie security (see also: BASE_URL, USE_BEHIND_PROXY)
_tls_flag = os.environ.get('SECURE_SSL_REDIRECT', '').strip().lower()
_base_for_tls = env('BASE_URL', default='')
_https_from_base = isinstance(_base_for_tls, str) and _base_for_tls.lower().startswith('https://')
if _tls_flag in ('true', '1', 'yes', 'on'):
    SECURE_SSL_REDIRECT = True
elif _tls_flag in ('false', '0', 'no', 'off'):
    SECURE_SSL_REDIRECT = False
else:
    SECURE_SSL_REDIRECT = _https_from_base

_scookie = os.environ.get('SESSION_COOKIE_SECURE', '').strip().lower()
if _scookie in ('true', '1', 'yes', 'on'):
    SESSION_COOKIE_SECURE = True
elif _scookie in ('false', '0', 'no', 'off'):
    SESSION_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT

_ccookie = os.environ.get('CSRF_COOKIE_SECURE', '').strip().lower()
if _ccookie in ('true', '1', 'yes', 'on'):
    CSRF_COOKIE_SECURE = True
elif _ccookie in ('false', '0', 'no', 'off'):
    CSRF_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT

SECURE_HSTS_SECONDS = env('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

if env('USE_BEHIND_PROXY', default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS Configuration — localhost defaults; add production SPA origins via CORS_ALLOWED_ORIGINS (comma-separated)
_cors_from_env = env('CORS_ALLOWED_ORIGINS', default='', cast=list)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite dev server
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
if _cors_from_env:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys([*CORS_ALLOWED_ORIGINS, *_cors_from_env]))

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Account Lockout Configuration
ACCOUNT_LOCKOUT_ENABLED = os.environ.get('ACCOUNT_LOCKOUT_ENABLED', 'True').lower() == 'true'
MAX_LOGIN_ATTEMPTS = int(os.environ.get('MAX_LOGIN_ATTEMPTS', '5'))
LOCKOUT_DURATION = int(os.environ.get('LOCKOUT_DURATION', '900'))  # 15 minutes

# GET /api/core/deploy/status/ — requires header X-Deployment-Status-Secret when set; empty = disabled
DEPLOYMENT_STATUS_SECRET = env('DEPLOYMENT_STATUS_SECRET', default='')

# Licensing Configuration
LICENSE_SERVER_URL = env('LICENSE_SERVER_URL', default='')
CODECANYON_TOKEN = env('CODECANYON_TOKEN', default='')
CODECANYON_PRODUCT_ID = env('CODECANYON_PRODUCT_ID', default='')
# Comma-separated Envato item IDs → self-hosted plan tier (gateway). Empty BASIC/SAAS = use default only.
CODECANYON_BASIC_ITEM_IDS = env('CODECANYON_BASIC_ITEM_IDS', default='')
CODECANYON_SAAS_ITEM_IDS = env('CODECANYON_SAAS_ITEM_IDS', default='')
CODECANYON_DEFAULT_SELF_HOSTED_PLAN_TYPE = env('CODECANYON_DEFAULT_SELF_HOSTED_PLAN_TYPE', default='saas')
LICENSE_ENFORCEMENT_ENABLED = env('LICENSE_ENFORCEMENT_ENABLED', default=True, cast=bool)
LICENSE_OFFLINE_GRACE_HOURS = env('LICENSE_OFFLINE_GRACE_HOURS', default=72, cast=int)
# When last_gateway_contact_at ages without successful validate/heartbeat sync (self-hosted + enforcement).
LICENSE_STALE_CONTACT_ENFORCEMENT_ENABLED = env(
    'LICENSE_STALE_CONTACT_ENFORCEMENT_ENABLED', default=True, cast=bool
)
LICENSE_STALE_CONTACT_WARN_DAYS = env('LICENSE_STALE_CONTACT_WARN_DAYS', default=7, cast=float)
LICENSE_STALE_CONTACT_READONLY_DAYS = env('LICENSE_STALE_CONTACT_READONLY_DAYS', default=14, cast=float)
LICENSE_CACHE_TTL_SECONDS = env('LICENSE_CACHE_TTL_SECONDS', default=900, cast=int)
LICENSE_SERVER_TIMEOUT_SECONDS = env('LICENSE_SERVER_TIMEOUT_SECONDS', default=8, cast=int)
# Self-hosted → operator gateway: base URL for /activate/, /heartbeat/, /validate/ (v1).
# If empty, derived from LICENSE_SERVER_URL by stripping a trailing /validate path when possible.
LICENSE_GATEWAY_BASE_URL = env('LICENSE_GATEWAY_BASE_URL', default='')
# When True and PLATFORM_SAAS_ENABLED, expose /api/license-registry/v1/* and Envato-backed activate.
LICENSE_REGISTRY_API_ENABLED = env('LICENSE_REGISTRY_API_ENABLED', default=True, cast=bool)
# Optional: reject validate-by-token if last registry heartbeat is older than this (0 = disabled).
LICENSE_REGISTRY_HEARTBEAT_MAX_AGE_HOURS = env('LICENSE_REGISTRY_HEARTBEAT_MAX_AGE_HOURS', default=0, cast=int)
# Super-admin list: mark installation inactive if no heartbeat for this long.
LICENSE_REGISTRY_INACTIVE_AFTER_HOURS = env('LICENSE_REGISTRY_INACTIVE_AFTER_HOURS', default=72, cast=int)
LICENSE_REGISTRY_ACTIVATE_RATE_PER_MINUTE = env('LICENSE_REGISTRY_ACTIVATE_RATE_PER_MINUTE', default=20, cast=int)
LICENSE_REGISTRY_HEARTBEAT_RATE_PER_MINUTE = env('LICENSE_REGISTRY_HEARTBEAT_RATE_PER_MINUTE', default=60, cast=int)
LICENSE_REGISTRY_VALIDATE_RATE_PER_MINUTE = env('LICENSE_REGISTRY_VALIDATE_RATE_PER_MINUTE', default=120, cast=int)
LICENSE_REGISTRY_TICKET_INGEST_RATE_PER_MINUTE = env(
    'LICENSE_REGISTRY_TICKET_INGEST_RATE_PER_MINUTE', default=30, cast=int
)
# Super-admin reports: semver string for "on latest version" checks (e.g. 1.4.0). Empty = use max seen.
LICENSE_REGISTRY_LATEST_VERSION = env('LICENSE_REGISTRY_LATEST_VERSION', default='')
# Optional revenue display: cents × unique registry purchases when Envato price is unknown (0 = omit estimate).
LICENSE_REVENUE_ESTIMATE_UNIT_CENTS = env('LICENSE_REVENUE_ESTIMATE_UNIT_CENTS', default=0, cast=int)
# Optional MaxMind GeoLite2 Country mmdb path for install geography (empty = skip GeoIP).
GEOIP2_COUNTRY_DATABASE = env('GEOIP2_COUNTRY_DATABASE', default='')
# Reported to the license gateway on activate/heartbeat/validate (optional).
SCREENGRAM_APP_VERSION = env('SCREENGRAM_APP_VERSION', default='')

# Platform SaaS (multi-tenant super-admin, Stripe billing). Off by default for self-hosted license installs.
# DEPLOYMENT_MODE: saas | self_hosted | hybrid — see core.deployment.resolve_effective_platform_saas
from core.deployment import normalize_deployment_mode, resolve_effective_platform_saas

DEPLOYMENT_MODE = normalize_deployment_mode(env('DEPLOYMENT_MODE', default='hybrid'))
_PLATFORM_SAAS_ENV = env('PLATFORM_SAAS_ENABLED', default=True, cast=bool)
PLATFORM_SAAS_ENABLED = resolve_effective_platform_saas(DEPLOYMENT_MODE, _PLATFORM_SAAS_ENV)
# Self-hosted only: POST new tickets / customer replies to operator LICENSE_GATEWAY_BASE_URL …/tickets/ingest/
TICKET_OPERATOR_BRIDGE_ENABLED = env('TICKET_OPERATOR_BRIDGE_ENABLED', default=False, cast=bool)
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')
# Stripe Checkout / Customer Portal (optional — SaaS self-serve)
STRIPE_PRICE_ID = env('STRIPE_PRICE_ID', default='')
STRIPE_GRACE_PERIOD_DAYS = env('STRIPE_GRACE_PERIOD_DAYS', default=7, cast=int)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers for cross-origin requests
    'channels',  # Django Channels for WebSocket support
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT Authentication
    'rest_framework_simplejwt.token_blacklist',  # JWT refresh blacklist (session revoke)
    'setup',  # Setup/Installation wizard (must be early for middleware)
    'licensing',  # License management and enforcement
    'core',  # Core infrastructure (caching, rate limiting, audit, backup)
    'accounts',  # App for User management (must be before other apps)
    'saas_platform',  # SaaS platform admin (tenants, Stripe webhooks)
    'signage',  # App for Screen management
    'templates',  # App for Template management
    'commands',  # App for Command management
    'log',  # App for centralized logging and monitoring
    'notifications',  # App for notification system
    'bulk_operations',  # App for bulk operations
    'content_validation',  # App for content validation
    'analytics',  # App for analytics dashboard
    'tickets',  # Helpdesk ticket system (SaaS multi-tenant)
    'blog',  # Marketing blog (public + platform admin API)
    'drf_spectacular',  # OpenAPI/Swagger documentation
    'api_docs',  # API documentation configuration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be as high as possible)
    'setup.middleware.InstallationCheckMiddleware',  # Installation check middleware (must be early)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'licensing.middleware.LicenseEnforcementMiddleware',  # License gate for protected APIs
    'log.middleware.ErrorLoggingMiddleware',  # Error logging middleware (must be after auth)
    'core.middleware.JSONErrorResponseMiddleware',  # JSON error responses (must be after ErrorLoggingMiddleware)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.rate_limiting.RateLimitMiddleware',  # Rate limiting middleware

]

ROOT_URLCONF = 'Screengram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Screengram.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if SQLite should be used (fallback for development without Docker)
USE_SQLITE = env('USE_SQLITE', default=False, cast=bool)

if USE_SQLITE:
    # SQLite database (fallback for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL database (production/development with Docker)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME', default='pixelcast_signage_db'),
            'USER': env('DB_USER', default='pixelcast_signage_user'),
            'PASSWORD': env('DB_PASSWORD', default=''),
            'HOST': env('DB_HOST', default='127.0.0.1'),
            'PORT': env('DB_PORT', default='5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'full_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.abspath(os.path.normpath(str(BASE_DIR / 'staticfiles')))

# Media files (User-uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

# CRITICAL: Normalize MEDIA_ROOT to absolute path to prevent path traversal issues
# On Windows, this ensures paths like C:\Work\Project\...\media are properly normalized
MEDIA_ROOT = os.path.abspath(os.path.normpath(str(BASE_DIR / 'media')))
MEDIA_URL = '/media/'

# Base URL for building absolute URLs (used in serializers)
# In production, set this to your domain (e.g., 'https://yourdomain.com')
BASE_URL = env('BASE_URL', default='http://localhost:8000')
# Public SPA URL for password-reset and email links (Vite dev default)
PUBLIC_WEB_APP_URL = env('PUBLIC_WEB_APP_URL', default='http://localhost:5173')
# Enterprise SSO (OIDC/SAML) — off until IdP env vars are set
SSO_ENABLED = env('SSO_ENABLED', default=False, cast=bool)

# Public download link for Android TV player APK (served via GET /api/public/downloads/)
ANDROID_TV_APK_URL = env('ANDROID_TV_APK_URL', default='')

# OpenWeather integration (Weather widget backend fetch/cache)
OPENWEATHER_API_KEY = env('OPENWEATHER_API_KEY', default='')
OPENWEATHER_BASE_URL = env('OPENWEATHER_BASE_URL', default='https://api.openweathermap.org')
WEATHER_WIDGET = {
    'REFRESH_INTERVAL_SECONDS': env('WEATHER_REFRESH_INTERVAL_SECONDS', default=900, cast=int),
    'STALE_TTL_SECONDS': env('WEATHER_STALE_TTL_SECONDS', default=21600, cast=int),
    'HTTP_TIMEOUT_SECONDS': env('WEATHER_HTTP_TIMEOUT_SECONDS', default=5, cast=int),
    'FORECAST_DAYS': env('WEATHER_FORECAST_DAYS', default=5, cast=int),
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project

AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.middleware.drf_exception_handler',  # Custom JSON error handler
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.ScreenGramTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'accounts.serializers.ScreenGramTokenRefreshSerializer',
}

# Django Channels Configuration
ASGI_APPLICATION = 'Screengram.asgi.application'

# Channel Layers Configuration
# For development: use in-memory channel layer
# For production: use Redis
CHANNEL_LAYERS_BACKEND = env('CHANNEL_LAYERS_BACKEND', default='memory')

if CHANNEL_LAYERS_BACKEND == 'redis':
    REDIS_HOST = env('REDIS_HOST', default='127.0.0.1')
    REDIS_PORT = env('REDIS_PORT', default=6379, cast=int)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_HOST, REDIS_PORT)],
            },
        },
    }
else:
    # Use in-memory channel layer for development
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Security settings for screen communication
SCREEN_COMMUNICATION = {
    'TIMESTAMP_TOLERANCE': 300,  # 5 minutes
    'NONCE_CACHE_TIMEOUT': 3600,  # 1 hour
    'RATE_LIMIT_COMMANDS_PER_MINUTE': 60,
    'WEBSOCKET_TIMEOUT': 30,  # seconds
}

# File Storage Configuration
# Supports both Local File System and Amazon S3
# Set USE_S3_STORAGE=True in environment to use S3, otherwise uses local storage

USE_S3_STORAGE = False  # Set to True to use S3, False for local storage

if USE_S3_STORAGE:
    # AWS S3 Configuration
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # AWS Credentials (set via environment variables in production)
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'pixelcast-signage-content')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    
    # S3 Security Settings
    AWS_QUERYSTRING_AUTH = False  # Don't add query string auth to URLs (use signed URLs instead)
    AWS_S3_FILE_OVERWRITE = False  # Don't overwrite files with same name
    AWS_DEFAULT_ACL = 'private'  # Files are private by default
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache for 1 day
    }
    
    # Signed URL expiration (in seconds) - 1 hour default
    AWS_S3_SIGNED_URL_EXPIRATION = 3600
    
    # Custom domain (optional)
    # AWS_S3_CUSTOM_DOMAIN = 'cdn.example.com'
else:
    # Local File Storage (Development/Default)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Content Storage Settings
CONTENT_STORAGE = {
    'MAX_FILE_SIZE': 5 * 1024 * 1024 * 1024,  # 5 GB max file size
    'ALLOWED_IMAGE_TYPES': ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml'],
    'ALLOWED_VIDEO_TYPES': ['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime'],
    'ALLOWED_WEBVIEW_TYPES': ['text/html', 'application/xhtml+xml'],
    'SIGNED_URL_EXPIRATION': 3600,  # 1 hour for signed URLs
    'ENABLE_HASH_VALIDATION': True,  # Enable file integrity checking via hash
    'HASH_ALGORITHM': 'sha256',  # Hash algorithm for integrity checking
}

# Notification System Configuration
NOTIFICATIONS_ASYNC = True  # Use Celery for async delivery (set False for sync in development)
_notif_key = (os.environ.get('NOTIFICATION_ENCRYPTION_KEY') or '').strip()
if Fernet:
    NOTIFICATION_ENCRYPTION_KEY = (
        _notif_key if _notif_key else default_notification_encryption_key()
    )
else:
    NOTIFICATION_ENCRYPTION_KEY = _notif_key or None
    if not DEBUG and not _LOADING_TEST_SETTINGS and not NOTIFICATION_ENCRYPTION_KEY:
        raise ImproperlyConfigured(
            'Install cryptography and set NOTIFICATION_ENCRYPTION_KEY when DEBUG is False.'
        )

# Celery Configuration (for async notifications)
_celery_redis_host = env('REDIS_HOST', default='127.0.0.1')
_celery_redis_port = env('REDIS_PORT', default=6379, cast=int)
_celery_redis_password = env('REDIS_PASSWORD', default='')
_celery_auth = f":{_celery_redis_password}@" if _celery_redis_password else ""
_celery_redis_base_url = f"redis://{_celery_auth}{_celery_redis_host}:{_celery_redis_port}"

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=f'{_celery_redis_base_url}/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=f'{_celery_redis_base_url}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production: uncomment and configure one of the following SMTP backends
# Gmail SMTP example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your-email@gmail.com')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your-app-password')

# SendGrid example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')

# Generic SMTP example:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
# EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
# EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = 'no-reply@pixelcastsignage.com'

# OpenAPI/Swagger Documentation Settings
try:
    from .schema_settings import SPECTACULAR_SETTINGS
except ImportError:
    # Fallback if schema_settings doesn't exist yet
    SPECTACULAR_SETTINGS = {
        'TITLE': 'PixelCast Signage API',
        'DESCRIPTION': 'PixelCast Signage Digital Signage Management API',
        'VERSION': '1.0.0',
        'SCHEMA_PATH_PREFIX': '/api/',
    }

# Caching Configuration
# For production: use Redis
# For development: use LocMemCache (fallback)
USE_REDIS_CACHE = os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true'

if USE_REDIS_CACHE:
    redis_cache_url = env('REDIS_CACHE_URL', default='')
    if not redis_cache_url:
        redis_host = env('REDIS_HOST', default='127.0.0.1')
        redis_port = env('REDIS_PORT', default=6379, cast=int)
        redis_password = env('REDIS_PASSWORD', default='')
        redis_auth = f":{redis_password}@" if redis_password else ""
        redis_cache_url = f"redis://{redis_auth}{redis_host}:{redis_port}/1"

    # Use Django's built-in Redis cache backend (Django 5.2+)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': redis_cache_url,
            'OPTIONS': {
                # Optional: uncomment if using django-redis
                # 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'pixelcast-signage',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
        }
    }
else:
    # Development: use in-memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'pixelcast-signage-cache',
        }
    }

# Rate Limiting Configuration
RATE_LIMITING = {
    'ENABLED': os.environ.get('RATE_LIMITING_ENABLED', 'True').lower() == 'true',
    'STRATEGY': 'combined',  # 'user', 'ip', 'role', 'endpoint', 'combined'
    'DEFAULT_PER_MINUTE': 60,
    'DEFAULT_PER_HOUR': 1000,
    'DEFAULT_PER_DAY': 10000,
    
    # Per-role rate limits (overrides defaults)
    'PER_ROLE_LIMITS': {
        'Developer': {
            'per_minute': 200,
            'per_hour': 5000,
            'per_day': 50000,
        },
        'Manager': {
            'per_minute': 100,
            'per_hour': 2000,
            'per_day': 20000,
        },
        'Employee': {
            'per_minute': 30,
            'per_hour': 500,
            'per_day': 5000,
        },
        # Same generous limits as Manager — Visitors browse many sections; avoids 429 spam
        'Visitor': {
            'per_minute': 100,
            'per_hour': 2000,
            'per_day': 20000,
        },
    },
    
    # Endpoint-specific limits (optional)
    'ENDPOINTS': {
        # '/api/analytics/': {
        #     'strategy': 'user',
        #     'limits': {
        #         'per_minute': 30,
        #         'per_hour': 500,
        #     },
        # },
    },
}

# Backup Configuration
BACKUP_CONFIG = {
    'BACKUP_DIR': os.environ.get('BACKUP_DIR', BASE_DIR / 'backups'),
    'RETENTION_DAYS': int(os.environ.get('BACKUP_RETENTION_DAYS', '30')),
    'ENABLE_AUTO_BACKUP': os.environ.get('ENABLE_AUTO_BACKUP', 'False').lower() == 'true',
    'AUTO_BACKUP_SCHEDULE': {
        'database': 'daily',  # 'daily', 'weekly', 'monthly'
        'media': 'weekly',
        'full': 'monthly',
    },
    'BACKUP_TIME': '02:00',  # Time to run scheduled backups (UTC)
    'COMPRESSION': True,
    'ENCRYPTION': os.environ.get('BACKUP_ENCRYPTION', 'False').lower() == 'true',
}

# Audit Logging Configuration
AUDIT_LOGGING = {
    'ENABLED': os.environ.get('AUDIT_LOGGING_ENABLED', 'True').lower() == 'true',
    'LOG_READS': os.environ.get('AUDIT_LOG_READS', 'False').lower() == 'true',  # Log read operations
    'RETENTION_DAYS': int(os.environ.get('AUDIT_RETENTION_DAYS', '365')),  # Keep logs for 1 year
    'AUTO_CLEANUP': os.environ.get('AUDIT_AUTO_CLEANUP', 'True').lower() == 'true',
}
