# Generated by Django 5.2.9 on 2025-12-12 17:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'signage_schedule',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'signage_template',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the screen', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the screen', max_length=255)),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier', max_length=255, unique=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of the screen', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the screen', null=True)),
                ('auth_token', models.CharField(blank=True, db_index=True, help_text='Authentication token for device communication (auto-generated if not provided)', max_length=255, unique=True)),
                ('secret_key', models.CharField(blank=True, db_index=True, help_text='Secret key for secure device operations (auto-generated if not provided)', max_length=255, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the screen was registered')),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Last known IP address of the device', null=True)),
                ('is_online', models.BooleanField(default=False, help_text='Whether the screen is currently online')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last time a heartbeat was received from the device', null=True)),
                ('last_command_sent_at', models.DateTimeField(blank=True, help_text='Last time a command was sent to the device', null=True)),
                ('last_command_received_at', models.DateTimeField(blank=True, help_text='Last time a command response was received from the device', null=True)),
                ('last_template_update_at', models.DateTimeField(blank=True, help_text='Last time the template was updated on the device', null=True)),
                ('is_busy', models.BooleanField(default=False, help_text='Whether the screen is currently processing a command')),
                ('app_version', models.CharField(blank=True, help_text='Version of the signage application running on the device', max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, help_text='Operating system version of the device', max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, help_text='Model name/number of the device', max_length=255, null=True)),
                ('screen_width', models.PositiveIntegerField(blank=True, help_text='Screen width in pixels', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('screen_height', models.PositiveIntegerField(blank=True, help_text='Screen height in pixels', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('brightness', models.PositiveIntegerField(blank=True, help_text='Screen brightness level (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('reverse_landscape', 'Reverse Landscape'), ('reverse_portrait', 'Reverse Portrait')], default='landscape', help_text='Screen orientation', max_length=20)),
                ('last_error_message', models.TextField(blank=True, help_text='Last error message received from the device', null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Last synchronization status', max_length=100, null=True)),
                ('last_download_error', models.TextField(blank=True, help_text='Last download error message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('assigned_schedules', models.ManyToManyField(blank=True, help_text='Schedules assigned to this screen', related_name='screens', to='signage.schedule')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns or manages this screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_screens', to=settings.AUTH_USER_MODEL)),
                ('active_template', models.ForeignKey(blank=True, help_text='Currently active template assigned to this screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_screens', to='signage.template')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'db_table': 'signage_screen',
                'ordering': ['-registration_date', 'name'],
                'indexes': [models.Index(fields=['device_id'], name='signage_scr_device__2cde8e_idx'), models.Index(fields=['auth_token'], name='signage_scr_auth_to_010bfa_idx'), models.Index(fields=['is_online', 'last_heartbeat_at'], name='signage_scr_is_onli_bf1c04_idx'), models.Index(fields=['owner', 'is_online'], name='signage_scr_owner_i_27df54_idx')],
            },
        ),
    ]
