# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signage', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='active_template',
            field=models.ForeignKey(blank=True, help_text='Currently active template assigned to this screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_screens', to='templates.template'),
        ),
        migrations.AddField(
            model_name='screen',
            name='assigned_schedules',
            field=models.ManyToManyField(blank=True, help_text='Schedules assigned to this screen', related_name='screens', to='signage.schedule'),
        ),
        migrations.AddField(
            model_name='screen',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns or manages this screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_screens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pairingsession',
            name='screen',
            field=models.OneToOneField(blank=True, help_text='Screen that was paired using this session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_session', to='signage.screen'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['device_id'], name='signage_scr_device__2cde8e_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['auth_token'], name='signage_scr_auth_to_010bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['is_online', 'last_heartbeat_at'], name='signage_scr_is_onli_bf1c04_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['owner', 'is_online'], name='signage_scr_owner_i_27df54_idx'),
        ),
        migrations.AddIndex(
            model_name='pairingsession',
            index=models.Index(fields=['pairing_code', 'status'], name='signage_pai_pairing_23eafd_idx'),
        ),
        migrations.AddIndex(
            model_name='pairingsession',
            index=models.Index(fields=['pairing_token', 'status'], name='signage_pai_pairing_452ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='pairingsession',
            index=models.Index(fields=['status', 'expires_at'], name='signage_pai_status_2eddd2_idx'),
        ),
    ]
