# Generated by Django 5.2.9 on 2025-12-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_alter_screen_active_template_delete_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairing_code', models.CharField(db_index=True, help_text='6-digit numeric pairing code displayed on TV', max_length=6, unique=True)),
                ('pairing_token', models.CharField(db_index=True, help_text='Secure token for QR code pairing', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paired', 'Paired'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current status of the pairing session', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this pairing session expires')),
                ('paired_at', models.DateTimeField(blank=True, help_text='When this session was successfully paired', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this pairing session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this pairing session was last updated')),
                ('paired_by', models.ForeignKey(blank=True, help_text='User who completed the pairing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_sessions', to=settings.AUTH_USER_MODEL)),
                ('screen', models.OneToOneField(blank=True, help_text='Screen that was paired using this session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_session', to='signage.screen')),
            ],
            options={
                'verbose_name': 'Pairing Session',
                'verbose_name_plural': 'Pairing Sessions',
                'db_table': 'signage_pairing_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pairing_code', 'status'], name='signage_pai_pairing_23eafd_idx'), models.Index(fields=['pairing_token', 'status'], name='signage_pai_pairing_452ba3_idx'), models.Index(fields=['status', 'expires_at'], name='signage_pai_status_2eddd2_idx')],
            },
        ),
    ]
