# Generated by Django 5.0.1 on 2026-04-02 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_platform', '0002_backfill_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_grace_until',
            field=models.DateTimeField(blank=True, help_text='After failed payment, allow access until this time (dunning grace)', null=True),
        ),
        migrations.CreateModel(
            name='TenantApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('signing_secret', models.CharField(blank=True, help_text='HMAC secret (server-generated)', max_length=128)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
