# Generated by Django 5.0.1 on 2026-04-03 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_platform', '0003_saas_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Per-tenant feature toggles (beta / enterprise overrides)'),
        ),
        migrations.CreateModel(
            name='PlatformExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hosting', 'Hosting'), ('tools', 'Tools'), ('support', 'Support'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=32)),
                ('amount_cents', models.IntegerField(default=0)),
                ('spent_on', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['-spent_on'],
            },
        ),
    ]
