# Generated by Django 5.0.1 on 2026-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_platform', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='access_lock_reason',
            field=models.CharField(blank=True, default='', help_text='Optional reason shown in admin tools for lock.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='access_lock_until',
            field=models.DateTimeField(blank=True, help_text='Optional expiration for tenant lock; null means manually unlocked.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='access_locked',
            field=models.BooleanField(default=False, help_text='When True, sign-in is blocked for tenant users (Developer control).'),
        ),
        migrations.AlterField(
            model_name='platformexpense',
            name='category',
            field=models.CharField(choices=[('hosting', 'Hosting'), ('infrastructure', 'Infrastructure'), ('tools', 'Tools'), ('support', 'Support'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
