# Generated by Django 5.0.1 on 2026-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_platform', '0005_tenant_access_lock_reason_tenant_access_lock_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('stripe_promotion_code_id', models.CharField(help_text='Stripe Promotion Code id (promo_...)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PlatformBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_free_screen_limit', models.PositiveIntegerField(default=1, help_text='New SaaS tenants get this device_limit until they subscribe.')),
                ('trial_days_display', models.PositiveSmallIntegerField(default=14, help_text='Shown on marketing pages (trial length is configured in Stripe).')),
                ('checkout_allow_promotion_codes', models.BooleanField(default=True, help_text='Allow customers to enter Stripe promotion codes at Checkout.')),
            ],
            options={
                'verbose_name': 'Platform billing settings',
                'verbose_name_plural': 'Platform billing settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('free', 'Free'), ('bundle', 'Bundle (fixed screens)'), ('per_screen', 'Per screen'), ('vip', 'VIP (unlimited screens)')], db_index=True, max_length=16)),
                ('included_screens', models.PositiveIntegerField(blank=True, help_text='For bundle: e.g. 5. Null for per_screen/vip/free.', null=True)),
                ('is_unlimited', models.BooleanField(default=False, help_text='True for VIP (device_limit=null on tenant).')),
                ('stripe_price_id', models.CharField(blank=True, default='', help_text='Stripe Price id (recurring). Empty for free tier.', max_length=255)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum seats/screens for per_screen checkout.')),
                ('display_amount_cents', models.PositiveIntegerField(blank=True, help_text='Optional marketing display (e.g. base price); actual charge is Stripe.', null=True)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, default='', max_length=64)),
                ('highlight', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
    ]
