# Generated by Django 5.0.1 on 2026-04-04 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_legacy_digital_signage_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAIGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('skipped_quota', 'Skipped quota'), ('failed', 'Failed')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('requested_count', models.PositiveSmallIntegerField(default=0)),
                ('created_count', models.PositiveSmallIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogAISettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('openai_api_key_encrypted', models.TextField(blank=True, default='')),
                ('model', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('api_base_url', models.URLField(default='https://api.openai.com/v1', help_text='OpenAI API base, trailing /v1', max_length=512)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='System instructions prepended to each generation request.')),
                ('keyword_pool', models.TextField(blank=True, default='', help_text='One topic or keyword per line (or comma-separated) for SEO-focused posts.')),
                ('posts_per_run', models.PositiveSmallIntegerField(default=2)),
                ('max_posts_per_day', models.PositiveSmallIntegerField(default=2)),
                ('auto_publish', models.BooleanField(default=False, help_text='If true, AI posts are published immediately; otherwise draft.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog AI settings',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.blogaigenerationlog'),
        ),
    ]
