# Generated by Django 5.2.9 on 2025-12-12 17:34

import django.core.validators
import django.db.models.deletion
import templates.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the template', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the template', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the template', null=True)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', help_text='Template orientation', max_length=20)),
                ('width', models.PositiveIntegerField(default=1920, help_text='Template width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=1080, help_text='Template height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview thumbnail image for the template', null=True, upload_to=templates.models.template_thumbnail_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is currently active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this template was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Template version number', validators=[django.core.validators.MinValueValidator(1)])),
                ('config_json', models.JSONField(default=templates.models.default_json_dict, help_text='Template configuration in JSON format (required)')),
                ('meta_data', models.JSONField(blank=True, default=templates.models.default_json_dict, help_text='Additional metadata in JSON format (optional)')),
                ('assigned_schedules', models.ManyToManyField(blank=True, help_text='Schedules assigned to this template', related_name='templates', to='signage.schedule')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('screens', models.ManyToManyField(blank=True, help_text='Screens that have this template assigned', related_name='templates', to='signage.screen')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates_template',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the layer', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the layer', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the layer', null=True)),
                ('x', models.PositiveIntegerField(default=0, help_text='X position (left) in pixels from template origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.PositiveIntegerField(default=0, help_text='Y position (top) in pixels from template origin', validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField(default=100, help_text='Layer width in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=100, help_text='Layer height in pixels', validators=[django.core.validators.MinValueValidator(1)])),
                ('z_index', models.PositiveIntegerField(default=0, help_text='Z-index for display order (higher values appear on top)', validators=[django.core.validators.MinValueValidator(0)])),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex code like #FFFFFF or color name)', max_length=50, null=True)),
                ('opacity', models.FloatField(default=1.0, help_text='Layer opacity (0.0 = transparent, 1.0 = opaque)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('animation_type', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide', 'Slide')], default='none', help_text='Type of animation to apply to the layer', max_length=20)),
                ('animation_duration', models.FloatField(default=0.0, help_text='Animation duration in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the layer is currently active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this layer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this layer was last updated')),
                ('template', models.ForeignKey(help_text='Template that this layer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='templates.template')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'db_table': 'templates_layer',
                'ordering': ['template', 'z_index', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active', 'created_at'], name='templates_t_is_acti_e790f8_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_by', 'is_active'], name='templates_t_created_84b12d_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['orientation', 'is_active'], name='templates_t_orienta_4b8890_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['template', 'z_index'], name='templates_l_templat_c5cc72_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['template', 'is_active'], name='templates_l_templat_1ec82d_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['is_active', 'z_index'], name='templates_l_is_acti_9edc82_idx'),
        ),
    ]
