# Generated by Django 5.0.1 on 2026-04-03 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_platform', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(db_index=True, help_text='Human-readable ticket number, auto-incremented per tenant')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('api', 'API'), ('chat', 'Chat')], default='web', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='en', max_length=8)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_children', to='tickets.ticket')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_canned_responses', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TicketCsatRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes visible only to agents')),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('api', 'API'), ('chat', 'Chat')], default='web', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tickets/attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected when no routing rule matches')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_queues', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketqueue'),
        ),
        migrations.CreateModel(
            name='TicketRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('merged_from', 'Merged From'), ('linked', 'Linked'), ('split_from', 'Split From'), ('parent', 'Parent'), ('child', 'Child')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='tickets.ticket')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='customer', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_role_profiles', to='saas_platform.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_role_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_busy', 'Least Busy'), ('manual', 'Manual')], default='round_robin', max_length=16)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Match criteria: priority, category, language, tags, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = higher precedence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='tickets.ticketqueue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_routing_rules', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='TicketSlaPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('first_response_minutes', models.PositiveIntegerField(help_text='Maximum minutes until first agent response')),
                ('resolution_minutes', models.PositiveIntegerField(help_text='Maximum minutes until ticket is resolved')),
                ('warning_threshold_pct', models.PositiveSmallIntegerField(default=80, help_text='Percentage of SLA time that triggers a warning (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sla_policies', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['tenant', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketslapolicy'),
        ),
        migrations.CreateModel(
            name='TicketSlaSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('first_response', 'First Response'), ('resolution', 'Resolution')], max_length=20)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('warning', 'Warning'), ('breached', 'Breached'), ('achieved', 'Achieved')], default='on_track', max_length=16)),
                ('target_at', models.DateTimeField(help_text='Deadline for this SLA metric')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_snapshots', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='saas_platform.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='tickets.tickettag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__6e203e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__edb166_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketqueue',
            index=models.Index(fields=['tenant', 'is_active'], name='tickets_tic_tenant__d3569d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketqueue',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketrelation',
            unique_together={('source', 'target', 'relation_type')},
        ),
        migrations.AddIndex(
            model_name='ticketroleprofile',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='tickets_tic_tenant__aa212c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketroleprofile',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='ticketroutingrule',
            index=models.Index(fields=['tenant', 'is_active', 'priority_order'], name='tickets_tic_tenant__0f8429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketslapolicy',
            unique_together={('tenant', 'priority')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'status'], name='tickets_tic_tenant__c58352_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'assignee'], name='tickets_tic_tenant__755322_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'priority'], name='tickets_tic_tenant__c84d54_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'queue'], name='tickets_tic_tenant__c859a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'created_at'], name='tickets_tic_tenant__ebb48d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'first_response_due_at'], name='tickets_tic_tenant__a9c3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'resolution_due_at'], name='tickets_tic_tenant__a1b20e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester', 'status'], name='tickets_tic_request_43654c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='ticketslasnapshot',
            index=models.Index(fields=['status', 'target_at'], name='tickets_tic_status_7fe6d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketslasnapshot',
            unique_together={('ticket', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='tickettag',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tickettagging',
            unique_together={('ticket', 'tag')},
        ),
    ]
