# Generated by Django 5.0.1 on 2026-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_backfill_legacy_support_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_version',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional app version reported on the ticket (for support correlation)', max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deployment_context',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional: saas | self_hosted — how the customer runs the product', max_length=32),
        ),
    ]
