# Generated by Django 5.0.1 on 2026-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ensure_tv_catalog_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmailSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('delivery_mode', models.CharField(choices=[('console', 'Console (development)'), ('smtp', 'SMTP')], default='console', help_text='Console prints to logs; SMTP sends via configured host.', max_length=16)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='')),
                ('default_from_email', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System email settings',
                'verbose_name_plural': 'System email settings',
                'db_table': 'core_system_email_settings',
            },
        ),
    ]
