# Generated by Django 5.0.1 on 2026-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_saas_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememailsettings',
            name='last_smtp_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systememailsettings',
            name='last_smtp_test_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systememailsettings',
            name='last_smtp_test_error_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='systememailsettings',
            name='last_smtp_test_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
