# Generated by Django 5.0.1 on 2026-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_system_email_last_test_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived logs are hidden from default queries but never deleted'),
        ),
    ]
