# Generated by Django 5.2.9 on 2025-12-16 16:44

import commands.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signage', '0002_alter_screen_active_template_delete_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the command', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional description or name for the command', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this command was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this command was last updated')),
                ('type', models.CharField(choices=[('restart', 'Restart'), ('refresh', 'Refresh'), ('change_template', 'Change Template'), ('display_message', 'Display Message'), ('sync_content', 'Sync Content'), ('custom', 'Custom')], help_text='Type of command to execute', max_length=50)),
                ('payload', models.JSONField(blank=True, default=commands.models.default_command_payload, help_text='Additional parameters for command execution (JSON format)')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority level (higher number = higher priority)', validators=[django.core.validators.MinValueValidator(0)])),
                ('expire_at', models.DateTimeField(blank=True, help_text='Command expires after this time (optional)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current status of the command', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When command execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When command execution completed', null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Last time command execution was attempted', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of times execution was attempted', validators=[django.core.validators.MinValueValidator(0)])),
                ('error_message', models.TextField(blank=True, help_text='Error message if command execution failed', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/sent this command', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commands', to=settings.AUTH_USER_MODEL)),
                ('screen', models.ForeignKey(help_text='Screen that should execute this command', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='signage.screen')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'db_table': 'commands_command',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['screen', 'status'], name='commands_co_screen__4f9d69_idx'), models.Index(fields=['screen', 'priority', 'status'], name='commands_co_screen__b00f83_idx'), models.Index(fields=['type', 'status'], name='commands_co_type_92d814_idx'), models.Index(fields=['status', 'created_at'], name='commands_co_status_6a784b_idx'), models.Index(fields=['expire_at', 'status'], name='commands_co_expire__e39750_idx'), models.Index(fields=['status', 'executed_at'], name='commands_co_status_17b257_idx'), models.Index(fields=['status', 'completed_at'], name='commands_co_status_eb0687_idx')],
            },
        ),
    ]
