# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='screen',
            field=models.ForeignKey(help_text='Screen that should execute this command', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='signage.screen'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['screen', 'status'], name='commands_co_screen__4f9d69_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['screen', 'priority', 'status'], name='commands_co_screen__b00f83_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['type', 'status'], name='commands_co_type_92d814_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'created_at'], name='commands_co_status_6a784b_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['expire_at', 'status'], name='commands_co_expire__e39750_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'executed_at'], name='commands_co_status_17b257_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'completed_at'], name='commands_co_status_eb0687_idx'),
        ),
    ]
