# Generated by Django 5.2.9 on 2025-12-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='active_template',
            field=models.ForeignKey(blank=True, help_text='Currently active template assigned to this screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_screens', to='templates.template'),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
