# Generated by Django 5.0.1 on 2026-03-29 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_initial'),
        ('templates', '0002_make_content_widget_nullable_and_add_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingsession',
            name='activation_delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the device token was delivered to the TV (one-time handshake)', null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='device_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the device token issued during pairing', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='device_token_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the current device token was issued', null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='last_paired_at',
            field=models.DateTimeField(blank=True, help_text='When this screen was last successfully paired', null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='token_revoked_at',
            field=models.DateTimeField(blank=True, help_text='When the device token was revoked (forces re-pair)', null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='auth_token',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy auth token (deprecated, use device_token_hash)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='secret_key',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy secret key (deprecated, use device_token_hash)', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['device_token_hash'], name='signage_scr_device__b35c96_idx'),
        ),
    ]
