# Generated by Django 5.0.1 on 2026-04-03 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
        ('saas_platform', '0005_tenant_access_lock_reason_tenant_access_lock_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLicenseState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(blank=True, default='', max_length=128)),
                ('license_status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('invalid', 'Invalid'), ('grace', 'Grace')], db_index=True, default='inactive', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_at', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('offline_grace_hours', models.PositiveIntegerField(default=72, help_text='Hours allowed offline before enforcement')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_state', to='saas_platform.tenant')),
            ],
            options={
                'verbose_name': 'Tenant License State',
                'db_table': 'licensing_tenant_state',
            },
        ),
        migrations.CreateModel(
            name='LicenseEnforcementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('decision', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_enforcement_logs', to='saas_platform.tenant')),
            ],
            options={
                'db_table': 'licensing_enforcement_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='licensing_e_tenant__748140_idx')],
            },
        ),
    ]
