# Generated by Django 5.0.1 on 2026-04-04 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_tenantlicensestate_licenseenforcementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRegistryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('envato_item_id', models.BigIntegerField(blank=True, null=True)),
                ('buyer_username', models.CharField(blank=True, default='', max_length=191)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('support_until', models.DateTimeField(blank=True, null=True)),
                ('license_type', models.CharField(blank=True, default='', max_length=64)),
                ('raw_sale', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registry purchase',
                'db_table': 'licensing_registry_purchase',
            },
        ),
        migrations.AddField(
            model_name='licensestate',
            name='activation_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LicenseRegistryInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=128)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('suspended', models.BooleanField(default=False)),
                ('suspended_reason', models.TextField(blank=True, default='')),
                ('suspicious', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='licensing.licenseregistrypurchase')),
            ],
            options={
                'db_table': 'licensing_registry_installation',
                'ordering': ['-last_heartbeat_at', '-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRegistryHeartbeatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat_logs', to='licensing.licenseregistryinstallation')),
            ],
            options={
                'db_table': 'licensing_registry_heartbeat_log',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['installation', 'received_at'], name='licensing_r_install_a101d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='licenseregistryinstallation',
            index=models.Index(fields=['purchase', 'domain'], name='licensing_r_purchas_24beaf_idx'),
        ),
    ]
