# Generated by Django 5.0.1 on 2026-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_registry_and_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='last_reported_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='last_screen_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='last_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='last_user_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='telemetry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
