# Generated by Django 5.0.1 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_registry_telemetry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensestate',
            name='features_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='licensestate',
            name='last_gateway_contact_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Last successful validate/heartbeat sync with operator gateway',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='licensestate',
            name='plan_type',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='basic | saas — from license gateway (Envato item mapping)',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='licenseregistryinstallation',
            name='plan_type_override',
            field=models.CharField(
                blank=True,
                default='',
                help_text='If set (basic|saas), overrides purchase.plan_type for this installation',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='licenseregistrypurchase',
            name='plan_type',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='basic | saas — derived from Envato item id (or operator override on install)',
                max_length=16,
            ),
        ),
    ]
