# Generated by Django 5.2.9 on 2025-12-22 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the audit log entry', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Username at time of action (for historical accuracy)', max_length=150)),
                ('user_role', models.CharField(blank=True, help_text='User role at time of action', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('execute', 'Execute'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('role_change', 'Role Change'), ('bulk_operation', 'Bulk Operation'), ('backup', 'Backup'), ('restore', 'Restore'), ('export', 'Export'), ('import', 'Import'), ('other', 'Other')], help_text='Type of action performed', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the action', max_length=20)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=255, null=True)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource (e.g., 'Screen', 'Template')", max_length=100)),
                ('resource_name', models.CharField(blank=True, help_text='Name or identifier of the resource', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON object describing what changed (before/after)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the affected resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_audit__user_id_66db5a_idx'), models.Index(fields=['action_type', 'timestamp'], name='core_audit__action__9c4f3a_idx'), models.Index(fields=['resource_type', 'timestamp'], name='core_audit__resourc_fdebc9_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_audit__ip_addr_f0c0f7_idx'), models.Index(fields=['severity', 'timestamp'], name='core_audit__severit_1e5fc9_idx'), models.Index(fields=['success', 'timestamp'], name='core_audit__success_fa56bf_idx'), models.Index(fields=['timestamp'], name='core_audit__timesta_75f997_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the backup', primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('database', 'Database'), ('media', 'Media Files'), ('full', 'Full System'), ('incremental', 'Incremental')], help_text='Type of backup', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', help_text='Current status of the backup', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to backup file (local or cloud)', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of backup file in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='Checksum/hash of backup file for integrity verification', max_length=128)),
                ('include_media', models.BooleanField(default=False, help_text='Whether media files are included')),
                ('compression', models.BooleanField(default=True, help_text='Whether backup is compressed')),
                ('encryption', models.BooleanField(default=False, help_text='Whether backup is encrypted')),
                ('scheduled', models.BooleanField(default=False, help_text='Whether this was an automated scheduled backup')),
                ('schedule_name', models.CharField(blank=True, help_text='Name of the schedule if scheduled', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional backup metadata')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When backup started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When backup completed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When backup expires (for retention policy)', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered the backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Backup',
                'verbose_name_plural': 'System Backups',
                'db_table': 'core_system_backup',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='core_system_status_03bedf_idx'), models.Index(fields=['backup_type', 'started_at'], name='core_system_backup__fb2783_idx'), models.Index(fields=['scheduled', 'started_at'], name='core_system_schedul_f14448_idx'), models.Index(fields=['expires_at'], name='core_system_expires_c63eba_idx')],
            },
        ),
    ]
