# Generated by Django 5.2.9 on 2026-01-02 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_user_id_f286cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_user_id_1cc5b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_type_28fae6_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='core_notifi_user_id_bd535f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='core_notifi_user_id_7862c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='core_notifi_type_82fbc5_idx'),
        ),
    ]
